[package]
name = "cml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
rand = "0.6.5"
lazy_static = "1.4.0"

[profile.release]
opt-level = 3